In [1]:
### Aufgabe_02_2.ipynb ###
# NumPy-Bibliothek importieren
import numpy as np

# NumPy-Array
ndArray = np.array([[5, 2, 1, 6, 0], [7, 3, 9, 4, 8]])

Berechnung der Quadratwurzel für jedes Element

In [22]:
ndArraySqrt = np.sqrt(ndArray)

Berechnung der kumulativen Summe über die Spalten

In [30]:
ndArrayCuSum = ndArray.cumsum(axis=1)
print(ndArrayCuSum)

[[ 5  7  8 14 14]
 [ 7 10 19 23 31]]


Maximum der beiden Teilarrays

In [33]:
ndArrayMax= ndArray.max(axis=1)
print(ndArrayMax)
#np.amax(ndArray)
np.maximum.reduce([ndArray[0],ndArray[1]])

[6 9]


array([7, 3, 9, 6, 8])

Addition der korrespondierenden Elemente der Teilarrays

In [42]:
#ndArrayAdd = ndArray.sum(axis=0)

ndArrayAdd = np.add(ndArray[0],ndArray[1])
print(ndArrayAdd)

[12  5 10 10  8]


Berechnung des Mittelwerts über die Zeilen

In [37]:
ndArrayMean = ndArray.mean(axis=0)
print(ndArrayMean)

[6.  2.5 5.  5.  4. ]


Anzahl der Zahlen größer als 3 (boolesche Arrays)

In [38]:
#ndArray[ndArray>3].shape[0]
#ndArray[ndArray>3]
ndArraySum = (ndArray >3).sum()
print(ndArraySum)

6


In [28]:
print("Array:         {}".format(ndArray))
print("Quadratwurzel: {}".format(ndArraySqrt))
print("Kum. Summe:    {}".format(ndArrayCuSum))
print("Maximum:       {}".format(ndArrayMax))
print("Addition:      {}".format(ndArrayAdd))
print("Mittelwert:    {}".format(ndArrayMean))
print("Zahlen > 3:    {}".format(ndArraySum))

Array:         [[5 2 1 6 0]
 [7 3 9 4 8]]
Quadratwurzel: [[2.23606798 1.41421356 1.         2.44948974 0.        ]
 [2.64575131 1.73205081 3.         2.         2.82842712]]
Kum. Summe:    [[ 5  2  1  6  0]
 [12  5 10 10  8]]
Maximum:       [6 9]
Addition:      [14 31]
Mittelwert:    [2.8 6.2]
Zahlen > 3:    6


In [ ]:
'''
Ausgabe:
Array:         [[5 2 1 6 0]
                [7 3 9 4 8]]
'''
### Ende Aufgabe_02_2.ipynb ###